import type { AnyDeviceDefinition, DeviceModelFactoryContext, SimulatedInboundCommand, SimulatedCommandOutcome, SimulatedState, SimulatedStateController, SimulatorScenario } from "../types.js";
export const STAGE_SHOW_SCENARIO_KEY="stage-show";
export const STAGE_SHOW_DEVICE_KEYS={dmx:"stage-dmx",fx:"stage-fx",safety:"stage-safety"} as const;
export const STAGE_SHOW_STATE_TOPICS={dmx:"switch/stage/dmx/state",fx:"switch/stage/fx/state",safety:"sensor/stage/safety"} as const;
export const STAGE_SHOW_COMMAND_TOPICS={dmx:"switch/stage/dmx/set",fx:"switch/stage/fx/set"} as const;
export const STAGE_SHOW_STIMULUS={trip:"stage/sim/safety-trip",resetSafety:"stage/sim/safety-reset",reset:"stage/sim/reset"} as const;
const INITIAL={dmx:{on:true,scene:"wash",master:72,universe:1,fixturesOnline:12,cueNumber:1,fromScene:"wash",transitioning:false,transitionMs:0,transitionStartedAt:0},fx:{active:false,effect:"none",haze:28,pulseMs:0,hitsToday:6,lastEffect:"none"},safety:{estop:false,fxLoopHealthy:true,doorClosed:true,pyroArmed:true,exclusionZoneClear:true,waterFxReady:true,state:"safe"}};
class Env{private c=new Map<string,SimulatedStateController>();private timers=new Set<ReturnType<typeof setTimeout>>();register(k:string,s:SimulatedStateController){this.c.set(k,s)}get(k:string){return this.c.get(k)}later(ms:number,f:()=>void){const t=setTimeout(()=>{this.timers.delete(t);f()},ms);this.timers.add(t)}clear(){for(const t of this.timers)clearTimeout(t);this.timers.clear()}reset(){this.clear();this.get(STAGE_SHOW_DEVICE_KEYS.dmx)?.update({...INITIAL.dmx},{forcePublish:true});this.get(STAGE_SHOW_DEVICE_KEYS.fx)?.update({...INITIAL.fx},{forcePublish:true});this.get(STAGE_SHOW_DEVICE_KEYS.safety)?.update({...INITIAL.safety},{forcePublish:true})}trip(){this.get(STAGE_SHOW_DEVICE_KEYS.safety)?.update({estop:true,fxLoopHealthy:false,pyroArmed:false,state:"tripped"},{forcePublish:true});this.get(STAGE_SHOW_DEVICE_KEYS.fx)?.update({active:false,effect:"none",pulseMs:0},{forcePublish:true})}resetSafety(){this.get(STAGE_SHOW_DEVICE_KEYS.safety)?.update({...INITIAL.safety},{forcePublish:true})}
 setDmx(s:SimulatedStateController,scene:string,master:number,transitionMs:number){const from=String(s.read().scene||"wash"),ms=Math.max(150,Math.min(4000,Math.round(transitionMs||900)));s.update({on:master>0,scene,master,fromScene:from,transitioning:true,transitionMs:ms,transitionStartedAt:Date.now(),cueNumber:Number(s.read().cueNumber??0)+1,fixturesOnline:12},{forcePublish:true});this.later(ms,()=>s.update({transitioning:false,fromScene:scene,transitionMs:0},{forcePublish:true}))}
 safeFor(effect:string):{ok:boolean;reason?:string}{const s=this.get(STAGE_SHOW_DEVICE_KEYS.safety)?.read()||{};if(s.estop===true||s.fxLoopHealthy===false)return{ok:false,reason:"physical FX safety loop open"};if(effect==="pyro"&&(s.pyroArmed!==true||s.exclusionZoneClear!==true))return{ok:false,reason:"pyro safety permissive unavailable"};if(effect==="rain"&&s.waterFxReady!==true)return{ok:false,reason:"water FX system not ready"};return{ok:true}}
 setFx(s:SimulatedStateController,effect:string,pulseMs:number,haze?:number){const nextHaze=haze===undefined?Number(s.read().haze??28):Math.max(0,Math.min(100,haze));s.update({active:true,effect,pulseMs,haze:effect==="haze"?Math.max(nextHaze,55):nextHaze,lastEffect:effect,hitsToday:Number(s.read().hitsToday??0)+1},{forcePublish:true});this.later(Math.max(300,Math.min(7000,pulseMs||1000)),()=>s.update({active:false,effect:"none",pulseMs:0},{forcePublish:true}))}dispose(){this.clear()}}
function sensor(key:string,name:string,topic:string,initial:SimulatedState,e:Env):AnyDeviceDefinition{return{key,name,stateTopic:topic,initialState:initial,createModel:(ctx)=>{e.register(ctx.key,ctx.state);return{getState:()=>ctx.state.read()}}}}
function actuator(key:string,name:string,stateTopic:string,commandTopic:string,initial:SimulatedState,e:Env,handler:(ctx:DeviceModelFactoryContext,c:SimulatedInboundCommand)=>SimulatedCommandOutcome):AnyDeviceDefinition{return{key,name,stateTopic,commandTopic,initialState:initial,commandProfile:{acknowledgement:{supported:true},qos:1},createModel:(ctx)=>{e.register(ctx.key,ctx.state);return{getState:()=>ctx.state.read(),onCommand:(c)=>handler(ctx,c)}}}}
export function createStageShowScenario():SimulatorScenario{const e=new Env();const dmx=actuator(STAGE_SHOW_DEVICE_KEYS.dmx,"DMX Show Controller",STAGE_SHOW_STATE_TOPICS.dmx,STAGE_SHOW_COMMAND_TOPICS.dmx,{...INITIAL.dmx},e,(ctx,c)=>{const scene=String(c.params.scene||"wash"),master=Number(c.params.master??72),transitionMs=Number(c.params.transitionMs??900);if(!["wash","verse","chorus","red","blackout","blue","gold","uv"].includes(scene)||!Number.isFinite(master))return{accepted:false,error:"invalid DMX scene/master"};const m=Math.max(0,Math.min(100,Math.round(master)));e.setDmx(ctx.state,scene,m,transitionMs);return{accepted:true,state:{patch:{on:m>0,scene,master:m,transitioning:true,transitionMs:Math.max(150,Math.min(4000,Math.round(transitionMs||900)))}}}});const fx=actuator(STAGE_SHOW_DEVICE_KEYS.fx,"Stage Multi-FX Rack",STAGE_SHOW_STATE_TOPICS.fx,STAGE_SHOW_COMMAND_TOPICS.fx,{...INITIAL.fx},e,(ctx,c)=>{const active=c.params.active;if(typeof active!=="boolean")return{accepted:false,error:"FX requires boolean active"};if(!active){ctx.state.update({active:false,effect:"none",pulseMs:0},{forcePublish:true});return{accepted:true,state:{patch:{active:false,effect:"none",pulseMs:0}}}}const effect=String(c.params.effect||"haze");if(!["haze","strobe","confetti","pyro","rain"].includes(effect))return{accepted:false,error:"unknown stage effect"};const safe=e.safeFor(effect);if(!safe.ok)return{accepted:false,error:safe.reason};const pulseMs=Number(c.params.pulseMs||1200),haze=Number(c.params.haze??ctx.state.read().haze??28);e.setFx(ctx.state,effect,pulseMs,haze);return{accepted:true,state:{patch:{active:true,effect,pulseMs,haze:effect==="haze"?Math.max(haze,55):haze,lastEffect:effect}}}});return{key:STAGE_SHOW_SCENARIO_KEY,devices:[dmx,fx,sensor(STAGE_SHOW_DEVICE_KEYS.safety,"Stage Safety & Permissive Loop",STAGE_SHOW_STATE_TOPICS.safety,{...INITIAL.safety},e)],stimuli:{[STAGE_SHOW_STIMULUS.trip]:()=>e.trip(),[STAGE_SHOW_STIMULUS.resetSafety]:()=>e.resetSafety(),[STAGE_SHOW_STIMULUS.reset]:()=>e.reset()},dispose:()=>e.dispose()}}
