import type { AnyDeviceDefinition, DeviceModelFactoryContext, SimulatedInboundCommand, SimulatedCommandOutcome, SimulatedState, SimulatedStateController, SimulatorScenario } from "../types.js";
export const STAGE_SHOW_SCENARIO_KEY="stage-show";
export const STAGE_SHOW_DEVICE_KEYS={dmx:"stage-dmx",fx:"stage-fx",safety:"stage-safety"} as const;
export const STAGE_SHOW_STATE_TOPICS={dmx:"switch/stage/dmx/state",fx:"switch/stage/fx/state",safety:"sensor/stage/safety"} as const;
export const STAGE_SHOW_COMMAND_TOPICS={dmx:"switch/stage/dmx/set",fx:"switch/stage/fx/set"} as const;
export const STAGE_SHOW_STIMULUS={trip:"stage/sim/safety-trip",resetSafety:"stage/sim/safety-reset",reset:"stage/sim/reset"} as const;
const INITIAL={dmx:{on:true,scene:"wash",master:72,universe:1,fixturesOnline:8,cueNumber:1},fx:{active:false,effect:"none",haze:34,pulseMs:0,hitsToday:6},safety:{estop:false,fxLoopHealthy:true,doorClosed:true,state:"safe"}};
class Env{private c=new Map<string,SimulatedStateController>();private timers=new Set<ReturnType<typeof setTimeout>>();register(k:string,s:SimulatedStateController){this.c.set(k,s)}get(k:string){return this.c.get(k)}later(ms:number,f:()=>void){const t=setTimeout(()=>{this.timers.delete(t);f()},ms);this.timers.add(t)}clear(){for(const t of this.timers)clearTimeout(t);this.timers.clear()}reset(){this.clear();this.get(STAGE_SHOW_DEVICE_KEYS.dmx)?.update({...INITIAL.dmx},{forcePublish:true});this.get(STAGE_SHOW_DEVICE_KEYS.fx)?.update({...INITIAL.fx},{forcePublish:true});this.get(STAGE_SHOW_DEVICE_KEYS.safety)?.update({...INITIAL.safety},{forcePublish:true})}trip(){this.get(STAGE_SHOW_DEVICE_KEYS.safety)?.update({estop:true,fxLoopHealthy:false,state:"tripped"},{forcePublish:true});this.get(STAGE_SHOW_DEVICE_KEYS.fx)?.update({active:false,effect:"none",pulseMs:0},{forcePublish:true})}resetSafety(){this.get(STAGE_SHOW_DEVICE_KEYS.safety)?.update({...INITIAL.safety},{forcePublish:true})}setDmx(s:SimulatedStateController,scene:string,master:number){s.update({on:master>0,scene,master,cueNumber:Number(s.read().cueNumber??0)+1,fixturesOnline:8})}setFx(s:SimulatedStateController,effect:string,pulseMs:number,haze?:number){const safe=this.get(STAGE_SHOW_DEVICE_KEYS.safety)?.read();if(safe&&(safe.estop===true||safe.fxLoopHealthy===false))return;const nextHaze=haze===undefined?Number(s.read().haze??34):Math.max(0,Math.min(100,haze));s.update({active:true,effect,pulseMs,haze:nextHaze,hitsToday:Number(s.read().hitsToday??0)+1});this.later(Math.max(300,Math.min(6000,pulseMs||1000)),()=>s.update({active:false,effect:"none",pulseMs:0},{forcePublish:true}))}dispose(){this.clear()}}
function sensor(key:string,name:string,topic:string,initial:SimulatedState,e:Env):AnyDeviceDefinition{return{key,name,stateTopic:topic,initialState:initial,createModel:(ctx)=>{e.register(ctx.key,ctx.state);return{getState:()=>ctx.state.read()}}}}
function actuator(key:string,name:string,stateTopic:string,commandTopic:string,initial:SimulatedState,e:Env,handler:(ctx:DeviceModelFactoryContext,c:SimulatedInboundCommand)=>SimulatedCommandOutcome):AnyDeviceDefinition{return{key,name,stateTopic,commandTopic,initialState:initial,commandProfile:{acknowledgement:{supported:true},qos:1},createModel:(ctx)=>{e.register(ctx.key,ctx.state);return{getState:()=>ctx.state.read(),onCommand:(c)=>handler(ctx,c)}}}}
export function createStageShowScenario():SimulatorScenario{const e=new Env();const dmx=actuator(STAGE_SHOW_DEVICE_KEYS.dmx,"DMX Show Controller",STAGE_SHOW_STATE_TOPICS.dmx,STAGE_SHOW_COMMAND_TOPICS.dmx,{...INITIAL.dmx},e,(ctx,c)=>{const scene=String(c.params.scene||"wash"),master=Number(c.params.master??72);if(!["wash","verse","chorus","red","blackout"].includes(scene)||!Number.isFinite(master))return{accepted:false,error:"invalid DMX scene/master"};e.setDmx(ctx.state,scene,Math.max(0,Math.min(100,Math.round(master))));return{accepted:true,state:{patch:{on:master>0,scene,master:Math.max(0,Math.min(100,Math.round(master))),fixturesOnline:8}}}});const fx=actuator(STAGE_SHOW_DEVICE_KEYS.fx,"Stage FX Controller",STAGE_SHOW_STATE_TOPICS.fx,STAGE_SHOW_COMMAND_TOPICS.fx,{...INITIAL.fx},e,(ctx,c)=>{const active=c.params.active;if(typeof active!=="boolean")return{accepted:false,error:"FX requires boolean active"};if(!active){ctx.state.update({active:false,effect:"none",pulseMs:0});return{accepted:true,state:{patch:{active:false,effect:"none",pulseMs:0}}}}const safe=e.get(STAGE_SHOW_DEVICE_KEYS.safety)?.read();if(safe&&(safe.estop===true||safe.fxLoopHealthy===false))return{accepted:false,error:"physical FX safety loop open"};const effect=String(c.params.effect||"haze"),pulseMs=Number(c.params.pulseMs||1200),haze=Number(c.params.haze??ctx.state.read().haze??34);e.setFx(ctx.state,effect,pulseMs,haze);return{accepted:true,state:{patch:{active:true,effect,pulseMs,haze}}}});return{key:STAGE_SHOW_SCENARIO_KEY,devices:[dmx,fx,sensor(STAGE_SHOW_DEVICE_KEYS.safety,"Stage Safety Loop",STAGE_SHOW_STATE_TOPICS.safety,{...INITIAL.safety},e)],stimuli:{[STAGE_SHOW_STIMULUS.trip]:()=>e.trip(),[STAGE_SHOW_STIMULUS.resetSafety]:()=>e.resetSafety(),[STAGE_SHOW_STIMULUS.reset]:()=>e.reset()},dispose:()=>e.dispose()}}
