// src/automations/custom-ui-manager.ts — Manages custom UI component files and registry generation

import fs from "node:fs";
import path from "node:path";
import logger from "../logger.js";

/** Base path within the project for custom component files. */
const CUSTOM_DIR = "frontend/src/components/panes/custom";

/** Header comment included at the top of every generated registry file. */
const REGISTRY_HEADER = `// ⚠️ AUTO-GENERATED — Do not edit manually.
// Regenerated by the Aeolus backend when custom UI components are saved or deleted.
`;

/**
 * Manages writing/deleting custom automation UI component `.tsx` files
 * and regenerating the static import registry consumed by the Vite build.
 */
export class CustomUiManager {
  private readonly customDir: string;

  constructor(private readonly projectDir: string) {
    this.customDir = path.join(projectDir, CUSTOM_DIR);
  }

  /** Check if the project directory and custom component subdirectory exist (or can be created). */
  isAvailable(): boolean {
    try {
      if (!fs.existsSync(this.projectDir)) return false;
      if (!fs.existsSync(this.customDir)) {
        fs.mkdirSync(this.customDir, { recursive: true });
      }
      return true;
    } catch {
      return false;
    }
  }

  /** Write a custom component file and regenerate the registry. */
  writeComponent(ruleId: string, uiSource: string): void {
    fs.mkdirSync(this.customDir, { recursive: true });
    const filePath = path.join(this.customDir, `automation-${ruleId}.tsx`);
    fs.writeFileSync(filePath, uiSource, "utf-8");
    logger.info({ ruleId, filePath }, "Wrote custom UI component file");
    this.regenerateRegistry();
  }

  /** Delete a custom component file (ENOENT is silently ignored) and regenerate the registry. */
  deleteComponent(ruleId: string): void {
    const filePath = path.join(this.customDir, `automation-${ruleId}.tsx`);
    try {
      fs.unlinkSync(filePath);
      logger.info({ ruleId, filePath }, "Deleted custom UI component file");
    } catch (err: unknown) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    }
    this.regenerateRegistry();
  }

  /**
   * Scan the custom/ directory for `automation-*.tsx` files and regenerate
   * `index.ts` with static imports and a `CUSTOM_COMPONENTS` map.
   */
  regenerateRegistry(): void {
    const registryPath = path.join(this.customDir, "index.ts");

    let files: string[] = [];
    try {
      files = fs
        .readdirSync(this.customDir)
        .filter(
          (f) =>
            f.startsWith("automation-") &&
            f.endsWith(".tsx") &&
            f !== "index.ts" &&
            f !== "types.ts",
        )
        .sort();
    } catch {
      // Directory may not exist yet — write an empty registry
    }

    const imports: string[] = [];
    const entries: string[] = [];

    for (const file of files) {
      const baseName = file.replace(/\.tsx$/, "");
      const ruleId = baseName.replace(/^automation-/, "");
      const importName = toPascalCase(baseName);
      imports.push(`import ${importName} from "./${baseName}";`);
      entries.push(`  "${ruleId}": ${importName},`);
    }

    const importBlock = imports.length > 0 ? imports.join("\n") + "\n" : "";
    const mapBody = entries.length > 0 ? "\n" + entries.join("\n") + "\n" : "";

    const content =
      REGISTRY_HEADER +
      "\n" +
      'import type { ComponentType } from "react";\n' +
      'import type { CustomComponentProps } from "./types";\n' +
      importBlock +
      "\n" +
      `export const CUSTOM_COMPONENTS: Record<string, ComponentType<CustomComponentProps>> = {${mapBody}};\n`;

    fs.writeFileSync(registryPath, content, "utf-8");
    logger.info({ count: files.length }, "Regenerated custom component registry");
  }
}

/**
 * Convert a kebab-case filename (e.g. `automation-abcd1234`) to PascalCase
 * (e.g. `AutomationAbcd1234`).
 */
function toPascalCase(str: string): string {
  return str
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}
