import express, { type Express } from "express";
import type { Database as DatabaseType } from "better-sqlite3";
import type { EventEmitter } from "node:events";
import jwt from "jsonwebtoken";
import cookieParser from "cookie-parser";
import { corsMiddleware } from "../api/middleware/cors-config.js";
import { requestLogger } from "../api/middleware/request-logger.js";
import { errorHandler } from "../api/middleware/error-handler.js";
import { authenticate } from "../auth/auth-middleware.js";
import { metricsMiddleware } from "../metrics/metrics-middleware.js";
import { createAuthRoutes } from "../api/routes/auth.routes.js";
import { createHealthRoutes } from "../api/routes/health.routes.js";
import { createDeviceRoutes } from "../api/routes/device.routes.js";
import { createStateRoutes } from "../api/routes/state.routes.js";
import { createAutomationRoutes } from "../api/routes/automation.routes.js";
import { createDataStoreRoutes } from "../api/routes/data-store.routes.js";
import { createLayoutRoutes } from "../api/routes/layout.routes.js";
import { createSystemRoutes } from "../api/routes/system.routes.js";
import { automationExists } from "../api/routes/automation.routes.js";
import { createResourceOwnershipStore } from "../auth/resource-ownership-store.js";
import { createCollectionOwnershipStore } from "../auth/collection-ownership-store.js";
import { createDeviceExposureResolver } from "../auth/device-exposure-resolver.js";
import { createAutomationScopeResolver } from "../automations/automation-scope-resolver.js";
import { createPermissionResolver } from "../auth/permission-resolver.js";
import { requireDevicePermission, requireAutomationPermission } from "../auth/auth-middleware.js";
import type { PermissionLevel } from "../auth/permission-service.js";
import { DeviceRegistry } from "../core/device-registry.js";
import { AutomationEngine } from "../automations/automation-engine.js";
import { CommandService, handlePublish, handleToggle, handleDeviceAction, handleLog, handleDelay, handleWebhook, type CommandServiceDeps } from "../automations/command-service.js";
import { ConditionRegistry } from "../automations/condition-registry.js";
import { ExecutionLog } from "../automations/execution-log.js";
import { AutomationStateStore } from "../automations/automation-state-store.js";
import { DataStore } from "../data-store/data-store.js";
import { _resetSecretCache } from "../auth/token-service.js";

// ─── Constants ───────────────────────────────────────────────────────────────

/**
 * Fixed JWT secret used for all test tokens.
 * Set as process.env.JWT_SECRET so the auth middleware verifies against it.
 */
export const TEST_JWT_SECRET = "aeolus-test-secret-do-not-use-in-production";

// ─── App Factory ─────────────────────────────────────────────────────────────

/**
 * Create a fully-wired Express app with all routes and middleware.
 * Uses the provided in-memory database for all persistence.
 *
 * Sets process.env.JWT_SECRET to a known test value so that tokens
 * generated by `createAuthToken()` are accepted by the auth middleware.
 */
export function createTestApp(
  db: DatabaseType,
  eventBus: EventEmitter,
): Express {
  // Set the JWT secret so the token service uses our known test secret
  process.env.JWT_SECRET = TEST_JWT_SECRET;
  _resetSecretCache();

  const app = express();

  // ─── Core Middleware ─────────────────────────────────────────────────────

  app.use(corsMiddleware);
  app.use(express.json({ limit: "1mb" }));
  app.use(cookieParser());
  app.use(requestLogger);
  app.use(metricsMiddleware());
  app.use(authenticate);

  // ─── Dependencies ────────────────────────────────────────────────────────

  const registry = new DeviceRegistry(db, eventBus);
  registry.loadFromDb();

  const dataStore = new DataStore(db, eventBus);

  // Automation authorization scope (shared by CommandService and — where wired —
  // the Sandbox). Built against the injected test `db`. Reused by the
  // resource-level authorization block below.
  const collectionOwnershipStore = createCollectionOwnershipStore(db);
  const deviceExposureResolver = createDeviceExposureResolver(registry, db);
  const automationScopeResolver = createAutomationScopeResolver(
    deviceExposureResolver,
    collectionOwnershipStore,
    db,
  );

  const actionExecutor = new CommandService({
    mqttService: createStubMqttService(),
    connectorManager: undefined,
    logger: createSilentLogger(),
    scopeResolver: automationScopeResolver,
  } as unknown as CommandServiceDeps);
  actionExecutor.registerHandler("publish", handlePublish);
  actionExecutor.registerHandler("toggle", handleToggle);
  actionExecutor.registerHandler("device_action", handleDeviceAction);
  actionExecutor.registerHandler("log", handleLog);
  actionExecutor.registerHandler("delay", handleDelay);
  actionExecutor.registerHandler("webhook", handleWebhook);

  const conditionRegistry = new ConditionRegistry();
  conditionRegistry.registerCondition("value_above", (v) => (context) => Number((context.state as Record<string, unknown>).value) > Number(v));
  conditionRegistry.registerCondition("value_below", (v) => (context) => Number((context.state as Record<string, unknown>).value) < Number(v));
  conditionRegistry.registerCondition("equals", (v) => (context) => String((context.state as Record<string, unknown>).value) === v);

  const executionLog = new ExecutionLog();
  const stateStore = new AutomationStateStore(db);
  stateStore.loadFromDb();

  const engine = new AutomationEngine(eventBus, { commandService: actionExecutor, executionLog });

  // Stub MQTT service for health route
  const stubMqttService = createStubMqttService();
  const startTime = Date.now();

  // ─── Resource-level authorization ──────────────────────────────────────────
  // Constructed against the injected test `db` so authorization reads the same
  // database as the rest of the app.
  const ownershipStore = createResourceOwnershipStore(db);
  // `deviceExposureResolver` is created earlier (it also backs the scope resolver).
  const permissionResolver = createPermissionResolver(ownershipStore, deviceExposureResolver, db);
  const requireDevice = (level: PermissionLevel) =>
    requireDevicePermission(level, {
      resolver: permissionResolver,
      exists: (id) => registry.getById(id) !== undefined,
    });
  const requireAutomation = (level: PermissionLevel) =>
    requireAutomationPermission(level, {
      resolver: permissionResolver,
      exists: (id) => automationExists(db, id),
    });

  // ─── Routes ──────────────────────────────────────────────────────────────

  app.use("/api/auth", createAuthRoutes());
  app.use("/api/devices", createDeviceRoutes(registry, actionExecutor, () => [], requireDevice, permissionResolver));
  app.use("/api/state", createStateRoutes(registry, permissionResolver));
  app.use("/api/health", createHealthRoutes(stubMqttService as never, registry, engine, startTime));
  app.use("/api/automations", createAutomationRoutes(
    engine,
    db,
    registry,
    actionExecutor,
    executionLog,
    "", // sandboxTypesPath — not needed for tests
    requireAutomation,
    permissionResolver,
    undefined, // connectorRegistry
    stateStore,
    conditionRegistry,
  ));
  app.use("/api/system", createSystemRoutes());
  app.use("/api/layout", createLayoutRoutes(db, permissionResolver));
  app.use("/api/data-store", createDataStoreRoutes(dataStore, permissionResolver, collectionOwnershipStore));

  // ─── Error Handler (must be last) ───────────────────────────────────────

  app.use(errorHandler);

  return app;
}

// ─── Auth Token Factory ──────────────────────────────────────────────────────

/**
 * Generate a valid JWT token for test requests.
 * The token is signed with TEST_JWT_SECRET and will be accepted
 * by the authenticate middleware when the test app is running.
 */
export function createAuthToken(options?: {
  userId?: string;
  username?: string;
  role?: "admin" | "user";
  groupId?: string | null;
}): string {
  const payload = {
    userId: options?.userId ?? "test-user-id",
    username: options?.username ?? "testuser",
    role: options?.role ?? "admin",
    groupId: options?.groupId ?? null,
  };
  return jwt.sign(payload, TEST_JWT_SECRET, { expiresIn: "15m" });
}

// ─── Internal Stubs ──────────────────────────────────────────────────────────

/** Minimal stub for MqttService used by health routes and action executor */
function createStubMqttService() {
  return {
    isConnected: () => false,
    publish: () => {},
    subscribe: () => {},
    unsubscribe: () => {},
    connect: async () => {},
    disconnect: async () => {},
  };
}

/** Silent logger that swallows all output during tests */
function createSilentLogger() {
  const noop = () => {};
  return {
    info: noop,
    warn: noop,
    error: noop,
    debug: noop,
    trace: noop,
    fatal: noop,
    child: () => createSilentLogger(),
  };
}
