// bunker-power — visual implementation behind ui/index.tsx
import { control, percent, CommandProofCard } from "@aeolus/ui";
export default function PowerSuppliesPanel({ model, actions }: {
    model: Record<string, any>;
    actions: Record<string, (...args: any[]) => void>;
}) { const battery = Number(model.battery ?? 74), solar = Number(model.solar ?? 1800), load = Number(model.load ?? 1200), net = Number(model.net ?? 600), gen = Boolean(model.generatorOn), genOutput = Number(model.generatorOutputW ?? 0), charging = Boolean(model.charging), fuel = Number(model.fuel ?? 62), food = Number(model.foodDays ?? 64), water = Number(model.waterDays ?? 80), waterLitres = Number(model.waterLitres ?? 8420), dailyLitres = Number(model.waterDailyLitres ?? 104), medChecked = Number(model.medicalCheckedDaysAgo ?? 12), occupants = Number(model.occupants ?? 4), beans = Number(model.beans ?? 312), pending = Boolean(model.pending), last = model.lastAction as any, color = battery < 30 ? "#ED846A" : battery < 45 ? "#E3B660" : "#79D397";
    // Aeolus starts backup generation itself, so the running generator is a state
    // the operator observes; only the opposite action stays pressable.
    const startVisual = control({ pending: pending && !gen, current: gen });
    const stopVisual = control({ pending: pending && gen, disabled: !gen });
    return <div style={{ padding: 11, minHeight: "100%", background: "#0B0D0B", color: "#EEF0EC" }}><div style={{ display: "flex", justifyContent: "space-between" }}><div><div style={{ fontSize: 12, fontWeight: 900 }}>POWER & SUPPLIES</div><div style={{ fontSize: 11, color: "#747C74", marginTop: 2 }}>Off-grid power reserve · automatic generation · shelter runway</div></div><div style={{ textAlign: "right" }}><div style={{ fontSize: 11, fontWeight: 850, color }}>{gen ? "GENERATOR " + Math.round(genOutput) + " W" : "SOLAR / BATTERY"}</div><div style={{ fontSize: 11, color: "#697169" }}>{percent(battery)} reserve · {charging ? "CHARGING" : "DISCHARGING"}</div></div></div><div style={{ border: "1px solid #333934", borderRadius: 10, padding: 8, background: "#0F120F", marginTop: 8 }}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 6 }}>{[["SOLAR", Math.round(solar) + " W", "#E4C768"], ["SITE LOAD", Math.round(load) + " W", "#9DB0A1"], ["NET", (net >= 0 ? "+" : "") + Math.round(net) + " W", net >= 0 ? "#75CF92" : "#E18368"]].map((m: any) => <div key={m[0]} style={{ border: "1px solid #2D332E", borderRadius: 7, padding: 7 }}><div style={{ fontSize: 11, color: "#6F776F" }}>{m[0]}</div><div style={{ fontSize: 13, fontFamily: "monospace", fontWeight: 850, color: m[2], marginTop: 2 }}>{m[1]}</div></div>)}</div><div style={{ marginTop: 8, height: 15, borderRadius: 8, background: "#1A1E1A", overflow: "hidden" }}><div style={{ height: "100%", width: Math.max(0, Math.min(100, battery)) + "%", background: "linear-gradient(90deg,#416F50," + color + ")" }}/></div><div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, color: "#737B73", marginTop: 3 }}><span>BATTERY {percent(battery)} · {charging ? "gaining" : "draining"}</span><span>GEN FUEL {percent(fuel)}</span></div></div><div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 6, marginTop: 7 }}>{/* Every figure says where it came from. Water is a tank the sensor is reading and a
        runway derived from it; food, beans and the medical kit are what somebody counted
        and wrote down. Presenting the second kind as though a sensor produced it was the
        thing worth fixing (§9.6, §13.4). */}
      {[["WATER", water + " days", Math.round(waterLitres) + " L · " + dailyLitres + " L/day", "TANK SENSOR", "#8FC7A0"], ["FOOD", food + " days", "for " + occupants + " occupants", "MANUAL INVENTORY", "#B9A87A"], ["BEANS", beans + " tins", "counted by hand", "MANUAL INVENTORY", "#B9A87A"], ["MEDICAL", "kit checked", medChecked + "d ago", "MANUAL / INSPECTION", "#B9A87A"]].map((m: any) => <div key={m[0]} style={{ border: "1px solid #333934", borderRadius: 8, padding: 7, background: "#0F120F" }}><div style={{ fontSize: 11, color: "#707870" }}>{m[0]}</div><div style={{ fontSize: 11, fontWeight: 800, color: "#C7CEC7", marginTop: 2 }}>{m[1]}</div><div style={{ fontSize: 10, color: "#6B736B", marginTop: 1 }}>{m[2]}</div><div style={{ fontSize: 9, fontWeight: 800, color: m[4], marginTop: 3, letterSpacing: ".04em" }}>{m[3]}</div></div>)}</div><div style={{ marginTop: 7, border: "1px solid #393D39", borderRadius: 9, padding: 8, background: "#0E110E" }}><div style={{ fontSize: 11, color: "#8B918B", letterSpacing: ".12em", marginBottom: 6 }}>OPERATOR CONTROLS</div><div style={{ display: "flex", gap: 5 }}><button {...startVisual} style={{ ...startVisual.style, flex: 1 }} onClick={() => actions.generatorOn()}>{pending && !gen ? "Starting generator…" : gen ? "Generator running" : "Start generator"}</button><button {...stopVisual} style={{ ...stopVisual.style, flex: 1 }} onClick={() => actions.generatorOff()}>{pending && gen ? "Stopping generator…" : "Stop generator"}</button></div>{/* The generator start is verified against measured output, so the receipt is
        worth showing beside the control that asked for it. */}<CommandProofCard evidence={model.lastCommand} label="Last command"/></div><div style={{ marginTop: 16, border: "1px dashed #685238", borderRadius: 9, padding: 8, background: "#171309" }}><div style={{ fontSize: 11, color: "#D7B771", letterSpacing: ".12em" }}>DEMO SCENARIO</div><div style={{ fontSize: 11, color: "#887655", margin: "3px 0 6px" }}>Collapse solar input and battery reserve. Aeolus should start backup generation itself.</div><div style={{ display: "flex", gap: 5 }}><button disabled={battery < 35} onClick={() => actions.simulateLowPower()} style={{ flex: 1, padding: "7px", borderRadius: 6, border: "1px solid #6A5031", background: "#20170C", color: "#E4B46B", fontSize: 11 }}>Cloud + low reserve</button><button onClick={() => actions.resetPower()} style={{ padding: "7px 10px", borderRadius: 6, border: "1px solid #48483E", background: "#161713", color: "#929287", fontSize: 11 }}>Reset</button></div></div><div style={{ fontSize: 11, color: "#626962", marginTop: 6 }}>{last?.label ? String(last.label) : "Bunker power online"}</div></div>; }
