// stage-show-sequencer — visual implementation behind ui/index.tsx
import { useEffect, useMemo, useState } from "react";
import { commandLadder, commandVerdict, control, percent, rungProps, verdictProps } from "@aeolus/ui";
type Cue = {
    id: number;
    label: string;
    scene: string;
    master: number;
    transitionMs: number;
    effect?: string;
    pulseMs?: number;
};
const LOOKS: any = { wash: { a: "#54D8FF", b: "#8759EF", floor: "#3359B8" }, verse: { a: "#3A72FF", b: "#E8A247", floor: "#172D67" }, chorus: { a: "#EF4CC4", b: "#43D8FF", floor: "#792C84" }, red: { a: "#FF4141", b: "#FF8A4B", floor: "#8A171B" }, blackout: { a: "#27313B", b: "#171C22", floor: "#07090B" }, blue: { a: "#3CA8FF", b: "#3151E8", floor: "#142D69" }, gold: { a: "#FFD16A", b: "#F78A4B", floor: "#7B4A16" }, uv: { a: "#A865FF", b: "#4B2BAF", floor: "#341B67" } };
const PRESETS: any = { wash: { label: "Open Wash", scene: "wash", master: 72, transitionMs: 1200 }, verse: { label: "Verse Blue", scene: "verse", master: 58, transitionMs: 1400 }, chorus: { label: "Chorus Lift", scene: "chorus", master: 92, transitionMs: 900 }, haze: { label: "Chorus + Haze", scene: "chorus", master: 88, transitionMs: 700, effect: "haze", pulseMs: 2600 }, confetti: { label: "Confetti Hit", scene: "gold", master: 100, transitionMs: 350, effect: "confetti", pulseMs: 1100 }, pyro: { label: "Pyro Hit", scene: "red", master: 100, transitionMs: 250, effect: "pyro", pulseMs: 700 }, rain: { label: "Rain Curtain", scene: "blue", master: 65, transitionMs: 900, effect: "rain", pulseMs: 3600 }, blackout: { label: "Blackout", scene: "blackout", master: 0, transitionMs: 700 } };
let seq = 100;
function make(k: string): Cue { return { id: seq++, ...PRESETS[k] }; }
export default function ShowControlDashboard({ model, actions }: {
    model: Record<string, any>;
    actions: Record<string, (...args: any[]) => void>;
}) {
    const scene = String(model.scene || "wash"), master = Number(model.master ?? 72), fixtures = Number(model.fixtures ?? 12), cueNo = Number(model.cueNumber ?? 1), pending = Boolean(model.pending), pendingFx = Boolean(model.pendingFx), fxActive = Boolean(model.fxActive), effect = String(model.effect || "none"), haze = Number(model.haze ?? 28), safe = model.safe !== false, estop = Boolean(model.estop), loop = model.loopHealthy !== false, pyro = Boolean(model.pyroArmed), exclusion = Boolean(model.exclusionClear), water = Boolean(model.waterReady), last = model.lastAction as any, c = LOOKS[scene] || LOOKS.wash;
    const [stack, setStack] = useState<Cue[]>(() => [make("wash"), make("verse"), make("haze"), make("confetti"), make("blackout")]);
    const [selected, setSelected] = useState(0);
    const [p, setP] = useState(0);
    useEffect(() => { const id = setInterval(() => setP(v => (v + 1) % 100000), 80); return () => clearInterval(id); }, []);
    const selectedCue = stack[selected] || stack[0];
    const busy = pending || pendingFx;
    const add = (k: string) => { setStack(s => [...s, make(k)]); setSelected(stack.length); };
    const move = (dir: number) => { setStack(s => { const n = [...s], to = Math.max(0, Math.min(n.length - 1, selected + dir)); if (to === selected)
        return n; const t = n[selected]; n.splice(selected, 1); n.splice(to, 0, t); setSelected(to); return n; }); };
    const remove = () => { if (stack.length <= 1)
        return; setStack(s => s.filter((_, i) => i !== selected)); setSelected(Math.max(0, selected - 1)); };
    const go = () => { if (!selectedCue || busy)
        return; actions.runCue(selectedCue as any); setSelected(i => Math.min(stack.length - 1, i + 1)); };
    const goVisual = control({ pending: busy });
    // An effect the physical safety loop has inhibited must look unavailable. Each
    // effect keeps its own colour while it is actually firable, since that coding
    // is how an operator finds the right button under show conditions.
    const fxVisual = (key: string) => busy
        ? control({ pending: true })
        : (key !== "stop" && !safe) ? control({ disabled: true }) : null;
    const verdict = commandVerdict(model.lastCommand), rungs = commandLadder(model.lastCommand);
 return <div style={{ padding: 14, minHeight: "100%", background: "linear-gradient(180deg,#090910,#050507)", color: "#F1F0F4" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12, marginBottom: 10 }}><div><div style={{ fontSize: 18, fontWeight: 900 }}>SHOW CONTROL</div><div style={{ fontSize: 12, color: "#85828D", marginTop: 3 }}>Lighting desk · local cue stack · smoke · confetti · pyro · rain FX</div></div><div style={{ textAlign: "right" }}><div style={{ fontSize: 12, fontWeight: 850, color: c.a }}>{scene.toUpperCase()} · {percent(master)}</div><div style={{ fontSize: 11, color: "#7E7A83", marginTop: 2 }}>physical cue {cueNo} · {fixtures}/12 fixtures · {safe ? "FX SAFE" : "FX INHIBITED"}</div></div></div>
    <div style={{ display: "grid", gridTemplateColumns: "1.35fr .65fr", gap: 10 }}><div style={{ border: "1px solid #292735", borderRadius: 13, overflow: "hidden", background: "#07070B" }}><svg width="100%" height="330" viewBox="0 0 760 300"><defs><linearGradient id="sf" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0D0C14"/><stop offset="1" stopColor={c.floor}/></linearGradient></defs><rect width="760" height="300" fill="url(#sf)" style={{ transition: "fill 900ms ease" }}/><rect x="82" y="221" width="596" height="40" rx="4" fill="#0B0A10" stroke="#302C3A"/>{[120, 205, 290, 375, 460, 545, 630].map((x, i) => { const sway = Math.sin((p + i * 9) * .045) * 18, col = i % 2 ? c.b : c.a, opacity = scene === "blackout" ? .04 : .2 + master / 145; return <g key={x}><circle cx={x} cy="34" r="11" fill="#17151D" stroke="#504A5A"/><path d={"M" + x + " 45 L" + (x - 52 + sway) + " 224 L" + (x + 52 + sway) + " 224 Z"} fill={col} opacity={opacity} style={{ transition: "fill 900ms ease, opacity 900ms ease" }}/><circle cx={x} cy="34" r="4" fill={col} opacity={scene === "blackout" ? .1 : .9} style={{ transition: "fill 900ms ease" }}/></g>; })}<rect x="313" y="155" width="134" height="66" rx="4" fill="#111019" stroke={c.a} style={{ transition: "stroke 900ms ease" }}/><text x="380" y="190" textAnchor="middle" fill={c.a} fontSize="14" fontWeight="900">AEOLUS LIVE</text>
    {(haze > 35 || effect === "haze") && Array.from({ length: 18 }).map((_, i) => <ellipse key={"h" + i} cx={65 + ((i * 43 + p * .6) % 635)} cy={115 + ((i * 31 + p * .2) % 110)} rx={18 + i % 3 * 7} ry={7 + i % 2 * 4} fill="#E2DEE7" opacity={effect === "haze" ? .08 : .035}/>)}
    {fxActive && effect === "confetti" && Array.from({ length: 34 }).map((_, i) => <rect key={i} x={80 + ((i * 71 + p * 3) % 610)} y={60 + ((i * 23 + p * 2) % 165)} width="4" height="7" transform={"rotate(" + ((i * 37 + p) % 180) + " " + (80 + ((i * 71 + p * 3) % 610)) + " " + (60 + ((i * 23 + p * 2) % 165)) + ")"} fill={["#FF6A9D", "#72D9FF", "#FFD767", "#9BFF8A"][i % 4]}/>)}
    {fxActive && effect === "pyro" && [150, 610].map((x, i) => <g key={x}><path d={"M" + x + " 220 Q" + (x - 18) + " 180 " + x + " 136 Q" + (x + 24) + " 181 " + x + " 220"} fill="#FF8A35" opacity=".9"/><path d={"M" + x + " 218 Q" + (x - 9) + " 187 " + x + " 158 Q" + (x + 11) + " 190 " + x + " 218"} fill="#FFE066"/></g>)}
    {fxActive && effect === "rain" && Array.from({ length: 28 }).map((_, i) => <line key={i} x1={75 + i * 22} y1={45 + ((p * 4 + i * 13) % 30)} x2={68 + i * 22} y2={155 + ((p * 4 + i * 13) % 45)} stroke="#6BC8FF" strokeWidth="1.4" opacity=".75"/>)}
    {fxActive && effect === "strobe" && <rect width="760" height="300" fill="#FFFFFF" opacity={(p % 6) < 2 ? .42 : .04}/>}<text x="18" y="287" fill="#716D78" fontSize="10">UNIVERSE 1 · MULTI-FX RACK · PHYSICAL SAFETY LOOP</text></svg></div>
    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}><div style={{ border: "1px solid #302D3B", borderRadius: 10, padding: 9, background: "#0B0A10" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ fontSize: 11, color: "#A09BA8", letterSpacing: ".08em" }}>LOCAL CUE STACK</div><div style={{ fontSize: 11, color: "#77727D" }}>this browser only</div></div><div style={{ maxHeight: 178, overflow: "auto", marginTop: 7 }}>{stack.map((q, i) => <button key={q.id} onClick={() => setSelected(i)} style={{ width: "100%", display: "grid", gridTemplateColumns: "25px 1fr auto", gap: 6, alignItems: "center", padding: "7px", marginBottom: 4, borderRadius: 7, border: "1px solid " + (selected === i ? "#6F5A86" : "#302C39"), background: selected === i ? "#19131F" : "#0F0E13", color: "#D6CFDA", textAlign: "left", cursor: "pointer" }}><span style={{ fontFamily: "monospace", fontSize: 11, color: selected === i ? "#C496E1" : "#77717D" }}>{String(i + 1).padStart(2, "0")}</span><span style={{ fontSize: 11, fontWeight: selected === i ? 800 : 600 }}>{q.label}</span><span style={{ fontSize: 11, color: q.effect ? "#F1B56F" : "#7599B0" }}>{q.effect ? q.effect.toUpperCase() : q.scene.toUpperCase()}</span></button>)}</div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 5, marginTop: 5 }}><button onClick={() => move(-1)} style={{ padding: "7px", fontSize: 11, borderRadius: 6, border: "1px solid #40384A", background: "#141118", color: "#AFA4B5" }}>↑ Up</button><button onClick={() => move(1)} style={{ padding: "7px", fontSize: 11, borderRadius: 6, border: "1px solid #40384A", background: "#141118", color: "#AFA4B5" }}>↓ Down</button><button onClick={remove} style={{ padding: "7px", fontSize: 11, borderRadius: 6, border: "1px solid #54343C", background: "#1A1013", color: "#D6909D" }}>Delete</button></div><button {...goVisual} onClick={go} style={{ ...goVisual.style, width: "100%", marginTop: 6, padding: "10px", fontSize: 13, fontWeight: 900 }}>{busy ? "VERIFYING…" : "GO → " + (selectedCue?.label || "CUE")}</button></div>
    <div style={{ border: "1px solid #302D3B", borderRadius: 10, padding: 9, background: "#0B0A10" }}><div style={{ fontSize: 11, color: "#A09BA8", letterSpacing: ".08em", marginBottom: 7 }}>ADD CUE</div><div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 5 }}>{[["wash", "WASH"], ["verse", "VERSE"], ["chorus", "CHORUS"], ["haze", "+ HAZE"], ["confetti", "CONFETTI"], ["pyro", "PYRO"], ["rain", "RAIN"], ["blackout", "BLACKOUT"]].map((x: any) => <button key={x[0]} onClick={() => add(x[0])} style={{ padding: "7px 2px", fontSize: 11, borderRadius: 6, border: "1px solid #3D3545", background: "#141118", color: x[0] === "pyro" ? "#FF9A72" : x[0] === "rain" ? "#78CBFF" : x[0] === "confetti" ? "#E7C66C" : "#BFAFC8" }}>{x[1]}</button>)}</div></div></div></div>
    <div style={{ display: "grid", gridTemplateColumns: "1.15fr .85fr", gap: 9, marginTop: 9 }}><div style={{ border: "1px solid #302D3B", borderRadius: 10, padding: 9, background: "#0B0A10" }}><div style={{ fontSize: 11, color: "#A09BA8", letterSpacing: ".08em", marginBottom: 7 }}>MANUAL EFFECTS</div><div style={{ display: "grid", gridTemplateColumns: "repeat(6,1fr)", gap: 6 }}>{[["haze", "SMOKE / HAZE", "#C4BCCB"], ["strobe", "STROBE", "#E9E9F0"], ["confetti", "CONFETTI", "#FFD06D"], ["pyro", "PYRO", "#FF8B63"], ["rain", "WATER / RAIN", "#65C9FF"], ["stop", "STOP FX", "#D48181"]].map((x: any) => { const unavailable = fxVisual(x[0]); return <button key={x[0]} {...(unavailable ?? { disabled: false })} onClick={() => x[0] === "stop" ? actions.stopFx() : actions.fireEffect({ effect: x[0] })} style={unavailable ? { ...unavailable.style, padding: "9px 3px", fontWeight: 800 } : { padding: "9px 3px", borderRadius: 7, border: "1px solid " + x[2] + "66", background: x[2] + "14", color: x[2], fontSize: 11, fontWeight: 800, cursor: "pointer" }}>{x[1]}</button>; })}</div></div>
    <div style={{ border: "1px solid " + (safe ? "#2E4938" : "#633C35"), borderRadius: 10, padding: 9, background: safe ? "#0D1510" : "#1B100D" }}><div style={{ display: "flex", justifyContent: "space-between" }}><div style={{ fontSize: 11, color: "#A09BA8", letterSpacing: ".08em" }}>PHYSICAL SAFETY</div><div style={{ fontSize: 11, fontWeight: 850, color: safe ? "#79D59A" : "#EF866F" }}>{safe ? "PERMISSIVE" : "INHIBIT"}</div></div><div style={{ display: "grid", gridTemplateColumns: "repeat(5,1fr)", gap: 4, marginTop: 7 }}>{[["E-STOP", !estop], ["FX LOOP", loop], ["PYRO", pyro], ["ZONE", exclusion], ["WATER", water]].map((m: any) => <div key={m[0]} style={{ textAlign: "center", padding: "6px 2px", borderRadius: 6, background: "#101113" }}><div style={{ width: 8, height: 8, borderRadius: 99, background: m[1] ? "#65CF8A" : "#E16D5D", margin: "0 auto 4px" }}/><div style={{ fontSize: 11, color: "#88858C" }}>{m[0]}</div></div>)}</div><div style={{ fontSize: 11, color: "#9A817A", marginTop: 16, marginBottom: 6, fontWeight: 800, letterSpacing: ".06em" }}>DEMO SCENARIO · inject physical safety state</div><div style={{ display: "flex", gap: 5 }}><button disabled={!safe} onClick={() => actions.simulateTrip()} style={{ flex: 1, padding: "7px", borderRadius: 6, border: "1px dashed #72443A", background: "#21110E", color: "#ED917E", fontSize: 11 }}>DEMO · Trip safety</button><button onClick={() => actions.resetSafety()} style={{ padding: "7px 10px", borderRadius: 6, border: "1px dashed #4D4A42", background: "#151513", color: "#99968E", fontSize: 11 }}>Reset</button></div></div></div>
    <div style={{ fontSize: 11, color: "#77727D", marginTop: 7 }}>{fxActive ? "Physical " + effect + " active · " + Math.round(haze) + "% haze" : last?.label ? String(last.label) : "Show controller ready"}</div>    {/* What the last command actually proved. Every rung is a durable record the
        runtime wrote, not a step this pane inferred from the outcome. */}
    {verdict && <div style={{ marginTop: 8, border: "1px solid #2E2A36", borderRadius: 9, padding: 9, background: "#100E14" }}>
      <div style={{ display: "flex", justifyContent: "space-between", gap: 8, marginBottom: 5 }}><div style={{ fontSize: 11, color: "#8C8696", letterSpacing: ".1em" }}>COMMAND EVIDENCE</div><div style={verdictProps(verdict)}>{verdict.headline}</div></div>
      {rungs.map((rung: any) => { const rv = rungProps(rung); return <div key={rung.state} style={rv.style}><span>{rv.mark}</span><span>{rung.label}</span>{rung.detail && <span style={{ color: "#787284" }}>{rung.detail}</span>}</div>; })}
      <div style={{ fontSize: 11, color: "#787284", marginTop: 5 }}>{verdict.clampNote || verdict.detail}</div>
    </div>}
    </div>;
}
