// ⚠️ AUTO-GENERATED — Do not edit manually.
// Regenerated by the Aeolus backend when custom UI components are saved or deleted.

import type { ComponentType } from "react";
import type { CustomComponentProps } from "./types";

export const CUSTOM_COMPONENTS: Record<string, ComponentType<CustomComponentProps>> = {};
