// vessel-rov — visual implementation behind ui/index.tsx
import { useEffect, useState } from "react";
export default function RovOperationsDashboard({ model, actions }: {
    model: Record<string, any>;
    actions: Record<string, (...args: any[]) => void>;
}) {
    const depth = Number(model.depth ?? 310), heading = Number(model.heading ?? 88), battery = Number(model.battery ?? 78), tether = Number(model.tetherTension ?? 310), altitude = Number(model.altitude ?? 8.2), visibility = Number(model.visibility ?? 14), thruster = Number(model.thrusterPct ?? 18);
    const mode = String(model.mode || "holding"), lights = model.lightsOn !== false, pending = Boolean(model.commandPending) || Boolean(model.tetherProtectionActive);
    const last = model.lastAction as any;
    const [phase, setPhase] = useState(0);
    useEffect(() => { const id = setInterval(() => setPhase(v => (v + 1) % 100000), 90); return () => clearInterval(id); }, []);
    const action = last?.label ? String(last.label) : "ROV telemetry online";
    const high = tether >= 650;
    const moving = mode === "diving" || mode === "recovering";
    const seabedY = 170;
    const rovY = Math.max(65, seabedY - Math.max(2, Math.min(30, altitude)) * 3.1);
    return <div style={{ padding: 11, minHeight: "100%", background: "linear-gradient(180deg,#061219,#041018)", color: "#EDF3F5" }}>
    <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 7 }}><div><div style={{ fontSize: 12, fontWeight: 900 }}>ROV OPERATIONS</div><div style={{ color: "#607B87", fontSize: 11, marginTop: 2 }}>Vehicle command · tether protection · seabed survey</div></div><div style={{ textAlign: "right" }}><div style={{ color: high ? "#F08E6B" : mode === "surveying" ? "#73DBA1" : "#63D1E8", fontSize: 11, fontWeight: 850 }}>{high ? "TETHER PROTECTION" : mode.toUpperCase()}</div><div style={{ color: "#5E737C", fontSize: 11 }}>{Math.round(depth)} m · battery {Math.round(battery)}%</div></div></div>
    <div style={{ display: "grid", gridTemplateColumns: "1.25fr .85fr", gap: 7 }}><div style={{ border: "1px solid #1B3A49", borderRadius: 10, overflow: "hidden", background: "#04131D" }}><svg width="100%" height="190" viewBox="0 0 330 190"><defs><linearGradient id="rovWater" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0A3046"/><stop offset="1" stopColor="#031019"/></linearGradient></defs><rect width="330" height="190" fill="url(#rovWater)"/><path d="M0 172 Q38 159 75 171 T150 169 T225 173 T330 164 L330 190 L0 190 Z" fill="#1D2925" stroke="#59634E"/><path d={"M25 22 C95 45 130 65 168 " + rovY} fill="none" stroke="#627B86" strokeDasharray="4 3"/>
      <g transform={"translate(170 " + rovY + ") rotate(" + (heading - 90) + ")"}><rect x="-22" y="-10" width="44" height="20" rx="5" fill="#102F3D" stroke={high ? "#E27D5D" : "#58D2ED"}/><circle cx="-12" cy="0" r="4" fill={lights ? "#B9F4FF" : "#4C626A"}/><path d="M22 -4 L33 -10 M22 4 L33 10" stroke="#58D2ED"/><circle cx="4" cy="0" r="2" fill="#77DDA0"/></g>
      {mode === "surveying" && Array.from({ length: 5 }).map((_, i) => <circle key={i} cx={205 + ((phase + i * 22) % 90)} cy={rovY + 18 + Math.sin((phase + i * 9) * .13) * 5} r="1.5" fill="#6ED6E9" opacity=".55"/>)}
      <line x1="214" y1={rovY} x2="214" y2={seabedY} stroke="#6FA0A8" strokeDasharray="2 3"/><text x="219" y={(rovY + seabedY) / 2} fill="#6D929C" fontSize="10">{altitude.toFixed(1)} m AGL</text><text x="10" y="18" fill="#5F7F8C" fontSize="10">VIS {visibility.toFixed(0)} m</text><text x="10" y="31" fill="#5F7F8C" fontSize="10">HDG {Math.round(heading)}°</text></svg></div>
      <div style={{ border: "1px solid #1B3A49", borderRadius: 10, background: "#07141B", padding: 9 }}><div style={{ color: "#687F89", fontSize: 11, letterSpacing: ".12em" }}>VEHICLE HEALTH</div><div style={{ marginTop: 9, color: "#697E87", fontSize: 11 }}>BATTERY</div><div style={{ display: "flex", alignItems: "baseline", gap: 4 }}><span style={{ fontSize: 19, fontWeight: 850, color: battery < 30 ? "#E98B68" : "#8CDBA0" }}>{Math.round(battery)}</span><span style={{ fontSize: 11, color: "#677B84" }}>%</span></div><div style={{ height: 5, background: "#17272E", borderRadius: 4, overflow: "hidden" }}><div style={{ height: "100%", width: Math.max(0, Math.min(100, battery)) + "%", background: battery < 30 ? "#D46D4E" : "#55AD70" }}/></div>
      <div style={{ marginTop: 12, color: "#697E87", fontSize: 11 }}>TETHER LOAD</div><div style={{ fontFamily: "monospace", fontSize: 14, fontWeight: 800, color: high ? "#F08A68" : "#C8D4D8", marginTop: 2 }}>{Math.round(tether)} N</div><div style={{ height: 5, background: "#17272E", borderRadius: 4, overflow: "hidden", marginTop: 3 }}><div style={{ height: "100%", width: Math.min(100, tether / 8) + "%", background: high ? "#D56646" : "#4DABC0" }}/></div><div style={{ marginTop: 11, color: "#697E87", fontSize: 11 }}>THRUSTER {Math.round(thruster)}%</div></div></div>
    <div style={{ marginTop: 7, border: "1px solid #263F4A", borderRadius: 9, padding: 8, background: "#07151D" }}><div style={{ color: "#80949D", fontSize: 11, letterSpacing: ".12em", marginBottom: 6 }}>OPERATOR CONTROLS</div><div style={{ display: "flex", gap: 5, flexWrap: "wrap" }}><button disabled={pending || moving} onClick={() => actions.rovDive()} style={{ flex: 1, minWidth: 75, padding: "7px", borderRadius: 6, border: "1px solid #2B5E70", background: "#0B2632", color: "#72D9EF", fontSize: 11, cursor: "pointer" }}>Dive 360 m</button><button disabled={pending || moving} onClick={() => actions.rovSurvey()} style={{ flex: 1, minWidth: 75, padding: "7px", borderRadius: 6, border: "1px solid #315B43", background: "#102219", color: "#83DA9C", fontSize: 11, cursor: "pointer" }}>Start transect</button><button disabled={pending} onClick={() => actions.rovHold()} style={{ padding: "7px 9px", borderRadius: 6, border: "1px solid #454A4C", background: "#171A1C", color: "#AAB4B8", fontSize: 11, cursor: "pointer" }}>Hold</button><button disabled={pending || moving} onClick={() => actions.rovRecover()} style={{ padding: "7px 9px", borderRadius: 6, border: "1px solid #5B4931", background: "#211A10", color: "#DDBB7B", fontSize: 11, cursor: "pointer" }}>Recover</button></div></div>
    <div style={{ marginTop: 7, border: "1px dashed #69502E", borderRadius: 9, padding: 8, background: "#171309" }}><div style={{ color: "#D8B66D", fontSize: 11, letterSpacing: ".12em" }}>DEMO SCENARIO</div><div style={{ color: "#806F50", fontSize: 11, margin: "3px 0 6px" }}>Inject a deep cross-current. High tether load should make Aeolus command a safe hold.</div><div style={{ display: "flex", gap: 5 }}><button onClick={() => actions.simulateRovCurrent()} style={{ flex: 1, padding: "6px", borderRadius: 6, border: "1px solid #6A5130", background: "#21180B", color: "#E3B866", fontSize: 11, cursor: "pointer" }}>Inject cross-current</button><button onClick={() => actions.resetRov()} style={{ padding: "6px 9px", borderRadius: 6, border: "1px solid #454138", background: "#171713", color: "#898B82", fontSize: 11, cursor: "pointer" }}>Reset mission</button></div></div>
    <div style={{ color: "#5A6F78", fontSize: 11, marginTop: 6, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{action}</div>
  </div>;
}
