// mine-dewatering — visual implementation behind ui/index.tsx
import { useEffect, useState } from "react";
import { commandLadder, commandVerdict, control, rungProps, toggleProps, verdictProps } from "@aeolus/ui";
function clamp(v: number, a: number, b: number) { return Math.min(b, Math.max(a, v)); }
export default function DewateringPanel({ model, actions }: {
    model: Record<string, any>;
    actions: Record<string, (...args: any[]) => void>;
}) {
    const level = Number(model.levelM ?? 1.8), inflow = Number(model.inflowLps ?? 18), discharge = Number(model.dischargeLps ?? 0), pump = Boolean(model.pumpOn), pumpFlow = Number(model.pumpFlowLps ?? 0), auto = model.autoEnabled !== false, pending = Boolean(model.commandPending), last = model.lastAction as any;
    const [phase, setPhase] = useState(0);
    useEffect(() => { const id = setInterval(() => setPhase(v => (v + 1) % 100000), 100); return () => clearInterval(id); }, []);
    const high = level >= 3.5, healthy = level <= 2.5;
    const color = high ? "#EF8968" : pump ? "#67CEE5" : "#79D89B";
    const action = last?.label ? String(last.label) : "Deep sump telemetry online";
    const waterY = 155 - clamp(level / 5, 0, 1) * 120;
    // Only one of the pair is ever available, so a pending request belongs to
    // whichever action the current pump state left reachable.
    const starting = pending && !pump, stopping = pending && pump;
    const startVisual = control({ pending: starting, current: pump });
    const stopVisual = control({ pending: stopping, disabled: !pump });
    const autoVisual = toggleProps(auto, { pending });
    const verdict = commandVerdict(model.lastCommand), rungs = commandLadder(model.lastCommand);
 return <div style={{ padding: 11, minHeight: "100%", background: "linear-gradient(180deg,#080D10,#06090B)", color: "#EDF2F4" }}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 8 }}><div><div style={{ fontSize: 12, fontWeight: 900 }}>DEWATERING</div><div style={{ fontSize: 11, color: "#6D7A81", marginTop: 2 }}>Deep sump level → automatic pump control → surface discharge</div></div><div style={{ textAlign: "right" }}><div style={{ fontSize: 11, fontWeight: 850, color }}>{high ? "HIGH LEVEL" : pump ? "PUMPING" : healthy ? "LEVEL NORMAL" : "WATCHING"}</div><div style={{ fontSize: 11, color: "#68757B" }}>{level.toFixed(1)} m</div></div></div>
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 7 }}><div style={{ border: "1px solid #263A43", borderRadius: 10, background: "#07131A", overflow: "hidden" }}><svg width="100%" height="180" viewBox="0 0 220 180"><rect width="220" height="180" fill="#07131A"/><path d="M43 22 V158 H152 V22" fill="#10191D" stroke="#46545B" strokeWidth="2"/><rect x="45" y={waterY} width="105" height={158 - waterY} fill="#0B5873" opacity=".8"/><path d={"M45 " + waterY + " Q68 " + (waterY - 3) + " 91 " + waterY + " T150 " + waterY} fill="none" stroke="#54C5E5"/><circle cx="119" cy="137" r="15" fill="#10191D" stroke={pump ? "#59CEE9" : "#4B5960"}/>{pump && <g style={{ transform: "rotate(" + (phase * 10) + "deg)", transformOrigin: "119px 137px" }}><line x1="108" y1="137" x2="130" y2="137" stroke="#59CEE9" strokeWidth="3"/><line x1="119" y1="126" x2="119" y2="148" stroke="#59CEE9" strokeWidth="3"/></g>}<path d="M134 137 H184 V36" fill="none" stroke="#44565F" strokeWidth="8"/><path d="M134 137 H184 V36" fill="none" stroke={pump ? "#4EC5E2" : "#607079"} strokeWidth="2"/>{pump && Array.from({ length: 5 }).map((_, i) => <circle key={i} cx={184} cy={124 - ((phase * 3 + i * 25) % 82)} r="2" fill="#70D7ED"/>)}<text x="55" y="16" fill="#6D818B" fontSize="10">DEEP SUMP</text><text x="196" y="34" textAnchor="end" fill="#697B84" fontSize="10">TO SURFACE</text></svg></div>
    <div style={{ border: "1px solid #263A43", borderRadius: 10, background: "#071117", padding: 9 }}>{[["LEVEL", level.toFixed(1) + " m"], ["INFLOW", Math.round(inflow) + " L/s"], ["DISCHARGE", Math.round(discharge) + " L/s"], ["PUMP", pump ? Math.round(pumpFlow) + " L/s" : "OFF"]].map((x: any) => <div key={x[0]} style={{ display: "flex", justifyContent: "space-between", padding: "7px 0", borderBottom: "1px solid #172830" }}><span style={{ fontSize: 11, color: "#6A7A82" }}>{x[0]}</span><span style={{ fontSize: 11, fontFamily: "monospace", fontWeight: 750, color: x[0] === "LEVEL" && high ? "#EF8968" : "#C2D0D5" }}>{x[1]}</span></div>)}<div style={{ marginTop: 8, fontSize: 11, color: "#5E7079" }}>AUTO START ≥ 3.5 m · STOP ≤ 1.5 m</div></div></div>
    <div style={{ marginTop: 7, border: "1px solid #293D46", borderRadius: 9, padding: 8, background: "#07141A" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}><div style={{ fontSize: 11, color: "#82949C", letterSpacing: ".12em" }}>OPERATOR CONTROLS</div><button {...autoVisual} style={{ ...autoVisual.style, borderRadius: 99, padding: "3px 7px" }} onClick={() => actions.toggleAuto()}>AUTO PUMPING {auto ? "ON" : "OFF"}</button></div><div style={{ display: "flex", gap: 5 }}><button {...startVisual} style={{ ...startVisual.style, flex: 1 }} onClick={() => actions.pumpOn()}>{starting ? "Starting pump…" : pump ? "Pump running" : "Start pump"}</button><button {...stopVisual} style={{ ...stopVisual.style, flex: 1 }} onClick={() => actions.pumpOff()}>{stopping ? "Stopping pump…" : "Stop pump"}</button></div></div>
    <div style={{ marginTop: 16, border: "1px dashed #6B5131", borderRadius: 9, padding: 8, background: "#171209" }}><div style={{ fontSize: 11, color: "#D3AF68", letterSpacing: ".12em" }}>DEMO SCENARIO</div><div style={{ fontSize: 11, color: "#837052", margin: "3px 0 6px" }}>Inject heavy groundwater inflow. With Auto on, Aeolus should start the physical sump pump and stop it after recovery.</div><div style={{ display: "flex", gap: 5 }}><button disabled={high} onClick={() => actions.simulateHeavyInflow()} style={{ flex: 1, padding: "6px", borderRadius: 6, border: "1px solid #68502E", background: "#22170B", color: "#E2B566", fontSize: 11, cursor: "pointer" }}>Inject heavy inflow</button><button onClick={() => actions.resetSump()} style={{ padding: "6px 9px", borderRadius: 6, border: "1px solid #454139", background: "#171713", color: "#918F87", fontSize: 11, cursor: "pointer" }}>Reset</button></div></div><div style={{ fontSize: 11, color: "#5E6D74", marginTop: 6, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{action}</div>    {/* What the last command actually proved. Every rung is a durable record the
        runtime wrote, not a step this pane inferred from the outcome. */}
    {verdict && <div style={{ marginTop: 8, border: "1px solid #33383E", borderRadius: 9, padding: 9, background: "#0E1114" }}>
      <div style={{ display: "flex", justifyContent: "space-between", gap: 8, marginBottom: 5 }}><div style={{ fontSize: 11, color: "#8A9299", letterSpacing: ".1em" }}>COMMAND EVIDENCE</div><div style={verdictProps(verdict)}>{verdict.headline}</div></div>
      {rungs.map((rung: any) => { const rv = rungProps(rung); return <div key={rung.state} style={rv.style}><span>{rv.mark}</span><span>{rung.label}</span>{rung.detail && <span style={{ color: "#6E767C" }}>{rung.detail}</span>}</div>; })}
      <div style={{ fontSize: 11, color: "#6E767C", marginTop: 5 }}>{verdict.clampNote || verdict.detail}</div>
    </div>}
    </div>;
}
