// bunker-perimeter — Automation Project logic
// The compiler wraps this module in Aeolus' execution/completion machinery.

export default async function run(context: EventContext) {
var topic=String(context.topic||"");var evt=topic.split("/").pop();function by(w){return devices.list().find(function(d){return d.topic===w;});}function action(l){state.set("lastAction",{label:l,at:Date.now()});}function summary(){events.emit("bunker/summary/perimeter",{contacts:Number(state.get("contacts")||0),sector:String(state.get("sector")||"east"),classification:String(state.get("classification")||"none"),lightsOn:Boolean(state.get("lightsOn")),autoLights:Boolean(state.get("autoLights"))});}function project(){if(state.get("autoLights")===undefined)state.set("autoLights",true);var l=by("switch/bunker/floodlights/state");state.set("lightsAvailable",Boolean(l));if(l)state.set("lightsOn",Boolean(l.state&&l.state.on));else if(state.get("lightsOn")===undefined)state.set("lightsOn",false);return Boolean(state.get("lightsOn"));}async function lights(on,why){var d=by("switch/bunker/floodlights/state");if(!d){action("Floodlight controller not reachable · no command issued");return false;}state.set("pending",true);var r=await devices.action(d.id,"command",{payload:{on:on}},{tier:"observed",deviceId:d.id,condition:{field:"on",op:"eq",value:on},timeoutMs:5000});state.set("pending",false);if(r&&r.success){state.set("lightsOn",on);action(why);return true;}action("Floodlight command not verified: "+String((r&&(r.error||r.lifecycleState))||"no result from the command boundary"));return false;}
var prev=state.get("lightsOn");var observed=project();var drifted=prev===undefined||Boolean(prev)!==observed;
if(topic.indexOf("ui/")===0){if(evt==="toggle-lights"){var wasAuto=Boolean(state.get("autoLights"));state.set("autoLights",false);if(!await lights(!observed,"Manual floodlight override · AUTO disabled"))state.set("autoLights",wasAuto);}else if(evt==="return-auto"){state.set("autoLights",true);var should=Number(state.get("contacts")||0)>0;if(observed!==should)await lights(should,"Perimeter floodlights returned to AUTO");else action("Perimeter floodlights returned to AUTO");}else if(evt==="simulate-contacts"){events.emit("bunker/sim/shambling-contacts",{});action("Injecting shambling contacts at the perimeter");}else if(evt==="clear-perimeter"){events.emit("bunker/sim/perimeter-clear",{});action("Clearing simulated perimeter contacts");}summary();return;}
if(topic!=="sensor/bunker/perimeter"){if(drifted)summary();return;}
var d=by(topic),s=d&&d.state?d.state:{};var contacts=Number(s.contacts||0);state.set("contacts",contacts);state.set("sector",String(s.sector||"east"));state.set("classification",String(s.classification||"none"));
if(Boolean(state.get("autoLights"))){var desired=contacts>0;if(observed!==desired){await lights(desired,desired?"AUTO · perimeter contact enabled floodlights":"AUTO · all clear, floodlights off");summary();return;}}
action(contacts>0?contacts+" perimeter contact"+(contacts===1?"":"s")+" · "+String(s.sector||"east")+" sector":"Perimeter clear. Probably just possums.");summary();
}
